# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Hexo CI

on:
  push:
    branches: [ source ]
  # pull_request:
  #   branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Checkout theme repo
      uses: actions/checkout@v2
      with:
        # repository: XPoet/hexo-theme-keep
        # ref: master
        # path: themes/keep
        repository: next-theme/hexo-theme-next
        ref: master
        path: themes/next
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    # https://sanonz.github.io/2020/deploy-a-hexo-blog-from-github-actions/
    - name: Install dependencies
      run: |
        npm install
    - name: Set up environment
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      run: |
        sudo timedatectl set-timezone "Asia/Shanghai"
        mkdir -p ~/.ssh
        echo "$DEPLOY_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        # cp _config.theme.yml themes/keep/_config.yml
        # cp images/* themes/keep/source/images/
        cp _config.next.yml themes/next/_config.yml
        cp images/* themes/next/source/images/
    - name: Deploy hexo
      run: |
        npm run deploy
